[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/video.mp4"
  to = "/video.mp4"
  status = 200
  force = true

[[headers]]
  for = "/video.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[plugins]]
  package = "@netlify/plugin-nextjs"
